"""
CDCS Enterprise Management Platform (CDCS-EMP)

Catering Module

Security package.
"""

from app.modules.catering.security.permissions import (
    CATERING_PERMISSIONS,
    CATERING_PRODUCT_CATEGORY_CREATE,
    CATERING_PRODUCT_CATEGORY_READ,
    CATERING_PRODUCT_CATEGORY_UPDATE,
    CATERING_PRODUCT_CATEGORY_DELETE,
    CATERING_PRODUCT_CREATE,
    CATERING_PRODUCT_READ,
    CATERING_PRODUCT_UPDATE,
    CATERING_PRODUCT_DELETE,
    CATERING_STOCK_ITEM_CREATE,
    CATERING_STOCK_ITEM_READ,
    CATERING_STOCK_ITEM_UPDATE,
    CATERING_STOCK_ITEM_DELETE,
    CATERING_INVENTORY_LOCATION_CREATE,
    CATERING_INVENTORY_LOCATION_READ,
    CATERING_INVENTORY_LOCATION_UPDATE,
    CATERING_INVENTORY_LOCATION_DELETE,
    CATERING_STOCK_BALANCE_READ,
    CATERING_STOCK_MOVEMENT_CREATE,
    CATERING_STOCK_MOVEMENT_READ,
    CATERING_STOCK_MOVEMENT_POST,
    CATERING_STOCK_TRANSFER_CREATE,
    CATERING_STOCK_TRANSFER_READ,
    CATERING_STOCK_TRANSFER_POST,
)

from .authorization import (
    AuthorizationEvaluator,
    CateringAuthorizationAdapter,
)


__all__ = [
    "CATERING_PERMISSIONS",
    "CATERING_PRODUCT_CATEGORY_CREATE",
    "CATERING_PRODUCT_CATEGORY_READ",
    "CATERING_PRODUCT_CATEGORY_UPDATE",
    "CATERING_PRODUCT_CATEGORY_DELETE",
    "CATERING_PRODUCT_CREATE",
    "CATERING_PRODUCT_READ",
    "CATERING_PRODUCT_UPDATE",
    "CATERING_PRODUCT_DELETE",
    "CATERING_STOCK_ITEM_CREATE",
    "CATERING_STOCK_ITEM_READ",
    "CATERING_STOCK_ITEM_UPDATE",
    "CATERING_STOCK_ITEM_DELETE",
    "CATERING_INVENTORY_LOCATION_CREATE",
    "CATERING_INVENTORY_LOCATION_READ",
    "CATERING_INVENTORY_LOCATION_UPDATE",
    "CATERING_INVENTORY_LOCATION_DELETE",
    "CATERING_STOCK_BALANCE_READ",
    "CATERING_STOCK_MOVEMENT_CREATE",
    "CATERING_STOCK_MOVEMENT_READ",
    "CATERING_STOCK_MOVEMENT_POST",
    "CATERING_STOCK_TRANSFER_CREATE",
    "CATERING_STOCK_TRANSFER_READ",
    "CATERING_STOCK_TRANSFER_POST",
    "AuthorizationEvaluator",
    "CateringAuthorizationAdapter",
]
