"""
CDCS Enterprise Management Platform (CDCS-EMP)

Catering Module

Security package.
"""

from app.modules.catering.security.permissions import (
    CATERING_PERMISSIONS,
    CATERING_PRODUCT_CATEGORY_CREATE,
    CATERING_PRODUCT_CATEGORY_READ,
    CATERING_PRODUCT_CATEGORY_UPDATE,
    CATERING_PRODUCT_CATEGORY_DELETE,
    CATERING_PRODUCT_CREATE,
    CATERING_PRODUCT_READ,
    CATERING_PRODUCT_UPDATE,
    CATERING_PRODUCT_DELETE,
)


__all__ = [
    "CATERING_PERMISSIONS",
    "CATERING_PRODUCT_CATEGORY_CREATE",
    "CATERING_PRODUCT_CATEGORY_READ",
    "CATERING_PRODUCT_CATEGORY_UPDATE",
    "CATERING_PRODUCT_CATEGORY_DELETE",
    "CATERING_PRODUCT_CREATE",
    "CATERING_PRODUCT_READ",
    "CATERING_PRODUCT_UPDATE",
    "CATERING_PRODUCT_DELETE",
]
