"""
CDCS Enterprise Management Platform (CDCS-EMP)

Expense Management Module

Security package.
"""

from app.modules.expense.security.permissions import (
    EXPENSE_CLASSIFICATION_CREATE,
    EXPENSE_CLASSIFICATION_READ,
    EXPENSE_CLASSIFICATION_UPDATE,
    EXPENSE_CLASSIFICATION_DELETE,
    EXPENSE_CREATE,
    EXPENSE_READ,
    EXPENSE_UPDATE,
    EXPENSE_DELETE,
    EXPENSE_PERMISSIONS,
)


__all__ = [
    "EXPENSE_CLASSIFICATION_CREATE",
    "EXPENSE_CLASSIFICATION_READ",
    "EXPENSE_CLASSIFICATION_UPDATE",
    "EXPENSE_CLASSIFICATION_DELETE",
    "EXPENSE_CREATE",
    "EXPENSE_READ",
    "EXPENSE_UPDATE",
    "EXPENSE_DELETE",
    "EXPENSE_PERMISSIONS",
]
