"""
CDCS Enterprise Management Platform (CDCS-EMP)

Procurement Security

Module-local security definitions.
"""

from .permissions import (
    PROCUREMENT_PERMISSIONS,
    PROCUREMENT_PURCHASE_REQUEST_APPROVE,
    PROCUREMENT_PURCHASE_REQUEST_CREATE,
    PROCUREMENT_PURCHASE_REQUEST_DELETE,
    PROCUREMENT_PURCHASE_REQUEST_READ,
    PROCUREMENT_PURCHASE_REQUEST_REJECT,
    PROCUREMENT_PURCHASE_REQUEST_RETURN,
    PROCUREMENT_PURCHASE_REQUEST_SUBMIT,
    PROCUREMENT_PURCHASE_REQUEST_UPDATE,
    PROCUREMENT_PURCHASE_REQUEST_LINE_CREATE,
    PROCUREMENT_PURCHASE_REQUEST_LINE_READ,
    PROCUREMENT_PURCHASE_REQUEST_LINE_UPDATE,
    PROCUREMENT_PURCHASE_REQUEST_LINE_DELETE,
    PROCUREMENT_PURCHASE_REQUIREMENT_CREATE,
    PROCUREMENT_PURCHASE_REQUIREMENT_DELETE,
    PROCUREMENT_PURCHASE_REQUIREMENT_READ,
    PROCUREMENT_PURCHASE_REQUIREMENT_UPDATE,
    PROCUREMENT_SUPPLIER_CREATE,
    PROCUREMENT_SUPPLIER_DELETE,
    PROCUREMENT_SUPPLIER_READ,
    PROCUREMENT_SUPPLIER_UPDATE,
    PROCUREMENT_PURCHASE_ORDER_CREATE,
    PROCUREMENT_PURCHASE_ORDER_READ,
    PROCUREMENT_PURCHASE_ORDER_UPDATE,
    PROCUREMENT_PURCHASE_ORDER_DELETE,
)


__all__ = [
    "PROCUREMENT_SUPPLIER_CREATE",
    "PROCUREMENT_SUPPLIER_READ",
    "PROCUREMENT_SUPPLIER_UPDATE",
    "PROCUREMENT_SUPPLIER_DELETE",
    "PROCUREMENT_PURCHASE_REQUIREMENT_CREATE",
    "PROCUREMENT_PURCHASE_REQUIREMENT_READ",
    "PROCUREMENT_PURCHASE_REQUIREMENT_UPDATE",
    "PROCUREMENT_PURCHASE_REQUIREMENT_DELETE",
    "PROCUREMENT_PURCHASE_REQUEST_CREATE",
    "PROCUREMENT_PURCHASE_REQUEST_READ",
    "PROCUREMENT_PURCHASE_REQUEST_UPDATE",
    "PROCUREMENT_PURCHASE_REQUEST_DELETE",
    "PROCUREMENT_PURCHASE_REQUEST_SUBMIT",
    "PROCUREMENT_PURCHASE_REQUEST_APPROVE",
    "PROCUREMENT_PURCHASE_REQUEST_REJECT",
    "PROCUREMENT_PURCHASE_REQUEST_RETURN",
    "PROCUREMENT_PURCHASE_REQUEST_LINE_CREATE",
    "PROCUREMENT_PURCHASE_REQUEST_LINE_READ",
    "PROCUREMENT_PURCHASE_REQUEST_LINE_UPDATE",
    "PROCUREMENT_PURCHASE_REQUEST_LINE_DELETE",
    "PROCUREMENT_PURCHASE_ORDER_CREATE",
    "PROCUREMENT_PURCHASE_ORDER_READ",
    "PROCUREMENT_PURCHASE_ORDER_UPDATE",
    "PROCUREMENT_PURCHASE_ORDER_DELETE",
    "PROCUREMENT_PERMISSIONS",
]
