"""add catering inventory domain models

Revision ID: 7491cd35c4bc
Revises: 8538697585d6
Create Date: 2026-09-04 02:14:55.097497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '7491cd35c4bc'
down_revision = '8538697585d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_locations',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('stock_items',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('minimum_level', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('stock_balances',
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stock_balances_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('stock_item_id', 'location_id', name='uq_stock_balance_item_location')
    )
    op.create_table('stock_transfers',
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('source_location_id', sa.Integer(), nullable=False),
    sa.Column('destination_location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'POSTED')", name='ck_stock_transfers_status'),
    sa.CheckConstraint('quantity > 0', name='ck_stock_transfers_quantity_positive'),
    sa.CheckConstraint('source_location_id <> destination_location_id', name='ck_stock_transfers_distinct_locations'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('stock_movements',
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.CheckConstraint("movement_type IN ('OPENING_BALANCE', 'RECEIPT', 'ISSUE', 'ADJUSTMENT', 'TRANSFER')", name='ck_stock_movements_type'),
    sa.CheckConstraint("status IN ('DRAFT', 'POSTED')", name='ck_stock_movements_status'),
    sa.CheckConstraint('quantity <> 0', name='ck_stock_movements_quantity_nonzero'),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movements')
    op.drop_table('stock_transfers')
    op.drop_table('stock_balances')
    op.drop_table('stock_items')
    op.drop_table('inventory_locations')
    # ### end Alembic commands ###
